### ISSUE TITLE
Error in _clear_database() if DB is empty

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#325]
In GitLab by @yoavnash on Jun 9, 2020, 12:53

It seems the function [`_clear_database()`](https://gitlab.cc-asp.fraunhofer.de/simphony/osp-core/-/blob/v3.4.0-dev/osp/core/session/db/sql_wrapper_session.py#L301) produces an error if the database is empty:
``` sh
Traceback (most recent call last):
  File "/ds-service/tests/base_class.py", line 33, in tearDown
    wrapper.session._clear_database()
  File "/usr/local/lib/python3.7/site-packages/osp_core-3.3.8-py3.7.egg/osp/core/session/db/sql_wrapper_session.py", line 324, in _clear_database
    raise e
  File "/usr/local/lib/python3.7/site-packages/osp_core-3.3.8-py3.7.egg/osp/core/session/db/sql_wrapper_session.py", line 308, in _clear_database
    self._registry.get(self.root).remove(rel=cuba.Relationship)
  File "/usr/local/lib/python3.7/site-packages/osp_core-3.3.8-py3.7.egg/osp/core/cuds.py", line 283, in remove
    raise RuntimeError("Did not remove any Cuds object, "
RuntimeError: Did not remove any Cuds object, because none matched your filter.
```

**Comment by urbanmatthias** [comment]
So one would need to check whether there is anything to remove in https://github.com/simphony/osp-core/blob/0da7b0ce18c1db9ea7b3ef91bd3dc2dd17f1b33a/osp/core/session/db/sql_wrapper_session.py#L311
