### ISSUE TITLE
Error importing validate_tree_against_schema

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#475]
``` sh
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from src import create_app, socketio
  File "/ds-service/src/__init__.py", line 9, in <module>
    from src.model import db, login_manager
  File "/ds-service/src/model.py", line 10, in <module>
    from src.dataspace import create_user_page
  File "/ds-service/src/dataspace.py", line 5, in <module>
    from osp.core.utils import validate_tree_against_schema
  File "/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/utils/__init__.py", line 2, in <module>
    from .general import *
  File "/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/utils/general.py", line 5, in <module>
    from osp.core.session.buffers import BufferContext
  File "/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/session/__init__.py", line 2, in <module>
    from osp.core.session.file_wrapper_session import FileWrapperSession
  File "/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/session/file_wrapper_session.py", line 2, in <module>
    from osp.core.session.wrapper_session import consumes_buffers
  File "/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/session/wrapper_session.py", line 6, in <module>
    from osp.core.utils import clone_cuds_object, \
ImportError: cannot import name 'clone_cuds_object' from partially initialized module 'osp.core.utils' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/osp_core-3.4.0-py3.8.egg/osp/core/utils/__init__.py)
```

@urbanmatthias

**Comment by aaronAB1993** [comment]
Are you sure that this is osp-core related? The tests for the validation util run successfully. Maybe you have a circular import somewhere in the ds-service?

**Comment by urbanmatthias** [comment]
Damn I can reproduce it. I think it was my fault, because I added some imports to utils. I wonder why the tests still work.

**Comment by urbanmatthias** [comment]
```
$ python
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osp.core.utils import validate_tree_against_schema
INFO:rdflib:RDFLib Version: 4.2.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/utils/__init__.py", line 2, in <module>
    from .general import *
  File "/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/utils/general.py", line 5, in <module>
    from osp.core.session.buffers import BufferContext
  File "/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/session/__init__.py", line 2, in <module>
    from osp.core.session.file_wrapper_session import FileWrapperSession
  File "/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/session/file_wrapper_session.py", line 2, in <module>
    from osp.core.session.wrapper_session import consumes_buffers
  File "/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/session/wrapper_session.py", line 6, in <module>
    from osp.core.utils import clone_cuds_object, \
ImportError: cannot import name 'clone_cuds_object' from partially initialized module 'osp.core.utils' (most likely due to a circular import) (/mnt/c/Users/urba/Desktop/repos/osp-core/osp/core/utils/__init__.py)
```
