### ISSUE TITLE
Problem with osp-core 3.5.2

### ISSUE THREAD

**Issue by aje08106** [simphony/osp-core#619]
Osp-core version 3.5.2 gives me an error. But with 3.5.1 program works just fine.

**Code :**
```python
from osp.wrappers.dataspace.dataspace_session import DataspaceSession
from osp.core.namespaces import cuba
import logging
import ssl

TRUST_SSL = True
if TRUST_SSL:
    ssl_context = ssl.SSLContext()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    ssl_kwargs = {'ssl': ssl_context}
else:
    ssl_kwargs = None

logging.getLogger("osp.core").setLevel(logging.ERROR)

USERNAME = 'xxx'
USER_PW = 'xxxxx'
HOST = 'xxxxx. xxx'
DATASPACE_NAME = 'xxxxxxx'

with DataspaceSession(
        f"wss://{USERNAME}:{USER_PW}@{HOST}/wrapper/",
        dataspace_name=DATASPACE_NAME,
        connect_kwargs=ssl_kwargs) as session:
    wrapper = cuba.Wrapper(session=session)
    wrapper.add(cuba.Entity(), rel=cuba.ActiveRelationship)
    wrapper.session.commit()

print('Connection successful.')
```
**Client side with osp-core 3.5.1 and server side with osp-core 3.5.2 stacktrace :** 
```
Traceback (most recent call last):
  File "connection_test.py", line 26, in <module>
    wrapper = cuba.Wrapper(session=session)
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/ontology/oclass.py", line 247, in __call__
    return Cuds(
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/cuds.py", line 82, in __init__
    self.session._store(self)
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/session/transport/transport_session_client.py", line 86, in _store
    self._engine.send(INITIALIZE_COMMAND,
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/session/transport/communication_engine.py", line 178, in send
    return event_loop.run_until_complete(
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/session/transport/communication_engine.py", line 223, in _request
    return self.handle_response(
  File "/home/ajesh/anaconda3/envs/intellitest/lib/python3.8/site-packages/osp_core-3.5.1-py3.8.egg/osp/core/session/transport/transport_session_client.py", line 145, in _receive
    raise RuntimeError("Error on Server side: %s" % data[7:])
RuntimeError: Error on Server side: ValueError: Unable to transform http://www.osp-core.com/cuds/#050fcd93-501b-456f-8f56-67b31cbadb40 to UUID.
```
When osp-core 3.5.2 runs on the server, above error happens. With osp-core 3.5.1, everything is fine! What could be the problem here?

**Comment by yoavnash** [comment]
> Client side with osp-core 3.5.1 and server side with osp-core 3.5.2 stacktrace

What happens when both client and server are set up with version 3.5.2?

**Comment by aje08106** [comment]
> > Client side with osp-core 3.5.1 and server side with osp-core 3.5.2 stacktrace
> 
> What happens when both client and server are set up with version 3.5.2?

**YES!** with client and server with version 3.5.2, everything works fine.

**Comment by aje08106** [comment]
> > Client side with osp-core 3.5.1 and server side with osp-core 3.5.2 stacktrace
> 
> What happens when both client and server are set up with version 3.5.2?

**YES!**  with version 3.5.2 on both sides, everything works fine!
