### ISSUE TITLE
Error when installing ontologies

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#670]
After updating to the new version of OSP-core (dev branch), I can no longer install some ontologies that I could before.

Traceback:
```sh
Traceback (most recent call last):
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\pico.py", line 65, in install_from_terminal
    ontology_installer.install(*args.files)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\ontology\installation.py", line 34, in install
    self._install(files, self._get_new_packages, False)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\ontology\installation.py", line 150, in _install
    self.namespace_registry.load_parser(parser)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\ontology\namespace_registry.py", line 378, in load_parser
    self._check_default_relationship_installed(ontology)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\ontology\namespace_registry.py", line 405, in _check_default_relationship_installed
    self.from_iri(ontology.default_relationship)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\osp\core\ontology\namespace_registry.py", line 151, in from_iri
    iri = rdflib.URIRef(iri)
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\rdflib\term.py", line 230, in __new__
    if not _is_valid_uri(value):
  File "c:\users\yoav\anaconda3\envs\osp\lib\site-packages\rdflib\term.py", line 79, in _is_valid_uri
    return all(map(lambda c: ord(c) > 256 or not c in _invalid_uri_chars, uri))
TypeError: 'NoneType' object is not iterable
ERROR 2021-07-14 14:26:25,909 [osp.core.pico]: Consider running 'pico --log-level debug install ...'
```

**Comment by yoavnash** [comment]
Example files will be sent separately.

**Comment by yoavnash** [comment]
Probably be related to https://github.com/simphony/osp-core/pull/658
