### ISSUE TITLE
Support RDFLib 6.0.0

### ISSUE THREAD

**Issue by kysrpex** [simphony/osp-core#677]
~~If one uses OSP-core with `rdflib==6.0.0`, the following exception is raised.~~

EDIT: This has been fixed in the dev branch. Now the issue focuses in supporting rdflib 6.0.0 in future releases.

------
```python
[jose@XXX osp-core]$ pico
Traceback (most recent call last):
  File "/home/jose/.local/bin/pico", line 5, in <module>
    from osp.core.pico import install_from_terminal
  File "/home/jose/.local/lib/python3.9/site-packages/osp/__init__.py", line 8, in <module>
    from osp.core.pico import compare_version as _compare_version
  File "/home/jose/.local/lib/python3.9/site-packages/osp/core/__init__.py", line 4, in <module>
    from osp.core.ontology.namespace_registry import namespace_registry \
  File "/home/jose/.local/lib/python3.9/site-packages/osp/core/ontology/__init__.py", line 3, in <module>
    from osp.core.ontology.oclass import OntologyClass
  File "/home/jose/.local/lib/python3.9/site-packages/osp/core/ontology/oclass.py", line 7, in <module>
    from osp.core.ontology.cuba import rdflib_cuba
  File "/home/jose/.local/lib/python3.9/site-packages/osp/core/ontology/cuba.py", line 49, in <module>
    rdflib_cuba = _CubaNamespace()
```

**Comment by kysrpex** [comment]
I reopen the issue so that the support for `rdflib==6.0.0` can be implemented.
